# Generated by Django 3.2.13 on 2022-05-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='topics',
            field=models.ManyToManyField(blank=True, to='news.Topic'),
        ),
    ]
